name: Checks code quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and setup uv
        run: |
          make setup_uv_venv
          make install_dev_requirements

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
