name: Checks code quality

on: [push]

jobs:
  code-checks:
    name: Checks quality of code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv and setup Python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.26"

      - name: Set up Python
        run: uv python install

      - name: Setup uv venv
        run: |
          uv venv && source .venv/bin/activate && make install_dev_requirements

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
